craiglist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('craiglist_app.urls')),
]

craiglist_app/urls.py
from django.urls import path
from . import views

app_name = 'craiglist_app'
urlpatterns = [
    path('', views.home, name='home'),
    path('new_search/', views.new_search, name='new_search'),
]

craiglist_app/models.py
from django.db import models

# Create your models here.
class Search(models.Model):
    search = models.CharField(max_length=500)
    created = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Searches'

    def __str__(self):
        return self.search

craiglist_app/views.py
from django.shortcuts import render
from requests.compat import quote_plus  #Automatically add %20 in spaces in your search
from bs4 import BeautifulSoup
import requests
from . import models

# Create your views here.
def home(request):
    return render(request, 'base.html')


def new_search(request):
    if request.method == 'POST':
        BASE_CRAIGLIST_URL = 'https://losangeles.craigslist.org/search/sss?query={}'
        search = request.POST.get('search')
        models.Search.objects.create(search=search)
        final_url = BASE_CRAIGLIST_URL.format(quote_plus(search))

        #Getting the webpage, creating a Response object.
        response = requests.get(final_url)

        #Extracting the source code of the page
        data = response.text

        #Passing the source code to Beautiful Soup to create a BeautifulSoup object for it.
        soup = BeautifulSoup(data, features='html.parser')

        #Extracting all the <li> tags whose class name is 'result-row' into a list
        post_listings = soup.find_all('li', {'class': 'result-row'})

        final_postings = []
        for post in post_listings:
            post_title = post.find(class_='result-title hdrlnk').text
            post_url = post.find('a').get('href')

            if post.find(class_='result-price'):
                post_price = post.find(class_='result-price').text
            else:
                post_price = 'N/A'

            if post.find(class_='result-image').get('data-ids'):
                post_image_id = post.find(class_='result-image').get('data-ids').split(',')[0].split(':')[1]
                post_image_url = "https://images.craiglist.org/{}_300x300.jpg".format(post_image_id)
                # print(post_image_url)
            else:
                post_image_url = 'https://losangeles.craigslist.org/images/peace.jpg'

            final_postings.append((post_title, post_url, post_price, post_image_url))

        context = {'search': search,
                   'final_postings': final_postings,
                   }

        return render(request, 'craiglist_app/new_search.html', context)
    return render(request, 'craiglist_app/new_search.html')

templates/base.html
{#{% load staticfiles %}#}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Joels' Craiglist Demo</title>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" href="{% static "craiglist_app/style.css" %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
<nav>
    <div class="container nav-wrapper">
        <a href="/" class="brand-logo">Joels' Craiglist Demo</a>
        <ul id="nav-mobile" class="right">
            <li><a href="/">Home</a></li>
        </ul>
    </div>
</nav>

<div class="container">
    <h1 style="text-align: center">What do you want to search for on Joels' Craiglist Demo?</h1>
    <div class="row">
        <div class="col s4">
            <!--Promo content 1 goes here-->
            <div class="center">
                <!-- Icons gotten from materialize icon-->
                <i class="large material-icons" style="color: #EE6E73">flash_on</i>
                <p>Fast craiglist web scraper</p>
                <p class="light center">Scrape away right here with a beautiful GUI.</p>
            </div>
        </div>

        <div class="col s4">
            <!-- Promo content 2 goes here -->
            <div class="center">
                <i class="large material-icons" style="color: orange">camera</i>
                <p class="light center">Built-in functionality to filter based on pricing</p>
            </div>
        </div>

        <div class="col s4">
            <!--Promo content 3 goes here-->
            <div class="center">
                <i class="large material-icons" style="color: blue">chrome_reader_mode</i>
                <p>A much sexier front-end to Craiglist</p>
                <p class="light center">Built with <span style="color: red">&hearts;</span></p>
            </div>
        </div>

    </div>

    <form action="{% url 'craiglist_app:new_search' %}" method="post">
        {% csrf_token %}
        <input type="text" name="search" placeholder="search">
{#        <input type="text" name="min-price" placeholder="minimum price">#}
{#        <input type="text" name="max-price" placeholder="maximum price">#}
        <button class="btn waves-effect waves-light" type="submit" name="action">Submit
            <i class="material-icons right">send</i>
        </button>
    </form>

    {% block content %}

    {% endblock %}
</div>


<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</body>
</html>

templates/craiglist_app/new_search.html
{% extends 'base.html' %}

{% block content %}
    <div class="center">
        <h3>You searched for: {{ search | title}}</h3>
    </div>

    <div class="row">
        {% for posting in final_postings %}
            <div class="col s4">
                <div class="card">
                    <div class="card-image">
                        <a href="{{ posting.1 }}"><img src="{{ posting.3 }}" alt=""></a>
                    </div>
                    <div class="card-content">
                        <p>{{ posting.0 }}</p>
                    </div>
                    <div class="card-action">
                        <a href="{{ posting.1 }}">View listing: Price {{ posting.2 }}</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock content %}